name: Terraform Validation AZURE

on:
  push:
    paths:
      - 'AZURE/**'
  pull_request:
    paths:
      - 'AZURE/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AZURE
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
  
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Format
      run: terraform fmt -recursive
      
    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate