name: OpenTofu Validation GCP

on:
  push:
    paths:
      - 'GCP/**'
  pull_request:
    paths:
      - 'GCP/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GCP
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.6.0
    
    - name: OpenTofu Init
      run: tofu init ## -backend=false
    
    - name: OpenTofu Format
      run: tofu fmt
      
    - name: OpenTofu Format Check
      run: tofu fmt -check -recursive

    - name: OpenTofu Validate
      run: tofu validate